<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <AssemblyName>CanDoItAll.FileTools.FileInteraction.Components</AssemblyName>
    <RootNamespace>CanDoItAll.FileTools.FileInteraction.Components</RootNamespace>
    <IsPackable>true</IsPackable>
    <Description>Blazor FileInteraction shell and lightweight viewers/editors.</Description>
    <Version>0.2.1</Version>
    <PackageVersion>0.2.1</PackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <SupportedPlatform Include="browser" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\CanDoItAll.FileTools.Abstractions\CanDoItAll.FileTools.Abstractions.csproj" />
    <ProjectReference Include="..\CanDoItAll.FileTools.FileInteraction.Core\CanDoItAll.FileTools.FileInteraction.Core.csproj" />
  </ItemGroup>
</Project>

