<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <IsPackable>false</IsPackable>
    <Version>0.1.0</Version>
    <PackageVersion>$(Version)</PackageVersion>
    <Authors>CanDoItAll</Authors>
    <Company>CanDoItAll</Company>
    <PackageProjectUrl>https://github.com/fyziktom/CanDoItAll.FileTools</PackageProjectUrl>
    <RepositoryUrl>https://github.com/fyziktom/CanDoItAll.FileTools</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DebugType>portable</DebugType>
    <PackageTags>CanDoItAll;Files;FileBrowser;FileInteraction</PackageTags>
  </PropertyGroup>
</Project>

